/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.igor.GUI;

import com.igor.factory.ConnectionFactory;
import com.igor.DAO.CompraDAO;
import com.igor.modelo.Compras;
import com.igor.modelo.Cores;
import com.igor.util.ReportUtils;
import java.awt.HeadlessException;
import java.io.InputStream;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author IgorDev e Artur
 */
public class consCompra extends javax.swing.JDialog {

    /**
     * Creates new form consCompra
     */
    private static javax.swing.table.DefaultTableModel tabela;
    private String usua;
    
    public consCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        jPb.setVisible(false);
        jDateChooser1.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnFundo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbVendas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTpesquisa = new javax.swing.JTextField();
        jSelecionar = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPnMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPb = new javax.swing.JProgressBar();
        jBtImprimirData = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jBtImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPnFundo.setBackground(new java.awt.Color(255, 255, 255));
        jPnFundo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTbVendas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTbVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod Compra", "Fornecedor", "Data Compra", "Nota Fiscal", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbVendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTbVendas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pesquisar por:");

        jTpesquisa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTpesquisaKeyPressed(evt);
            }
        });

        jSelecionar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSelecionar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Data", "Cliente", "Código" }));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPnMenu.setBackground(new java.awt.Color(51, 51, 255));

        jLabel2.setFont(new java.awt.Font("Aharoni", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Consulta de Compras");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/back_2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPb.setForeground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPnMenuLayout = new javax.swing.GroupLayout(jPnMenu);
        jPnMenu.setLayout(jPnMenuLayout);
        jPnMenuLayout.setHorizontalGroup(
            jPnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnMenuLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPb, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPnMenuLayout.setVerticalGroup(
            jPnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnMenuLayout.createSequentialGroup()
                .addComponent(jPb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jBtImprimirData.setText("Imprimir Por Data");
        jBtImprimirData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtImprimirDataActionPerformed(evt);
            }
        });

        jBtImprimir.setText("Imprimir Relatório");
        jBtImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnFundoLayout = new javax.swing.GroupLayout(jPnFundo);
        jPnFundo.setLayout(jPnFundoLayout);
        jPnFundoLayout.setHorizontalGroup(
            jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnFundoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jTpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtImprimirData, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPnFundoLayout.setVerticalGroup(
            jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnFundoLayout.createSequentialGroup()
                .addComponent(jPnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPnFundoLayout.createSequentialGroup()
                            .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPnFundoLayout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(jSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(6, 6, 6))
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(19, 19, 19))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnFundoLayout.createSequentialGroup()
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBtImprimirData, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)))
                    .addGroup(jPnFundoLayout.createSequentialGroup()
                        .addComponent(jBtImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTbVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbVendasMouseClicked
        if (evt.getClickCount() == 2) {
            Compras modelo = new Compras();
            //manda para os edits da tela cadastro e volta para a mesma

            Object obj0 = (jTbVendas.getValueAt(jTbVendas.getSelectedRow(), 0));
            modelo.setId_compra(Integer.parseInt(obj0.toString()));

            Object obj1 = (jTbVendas.getValueAt(jTbVendas.getSelectedRow(), 1));
            modelo.setFornecedor(obj1.toString());

            Object obj2 = (jTbVendas.getValueAt(jTbVendas.getSelectedRow(), 2));
            modelo.setDatac(obj2.toString());

            Object obj3 = (jTbVendas.getValueAt(jTbVendas.getSelectedRow(), 3));
            modelo.setN_notafiscal(obj3.toString());
            
            Object obj4 = (jTbVendas.getValueAt(jTbVendas.getSelectedRow(), 4));
            modelo.setValor_total(Double.parseDouble(obj4.toString()));

            //manda para outra tela com as informações nos edits
            TelaComprar dialog = new TelaComprar(new javax.swing.JFrame(), true);
            Cores cores = new Cores();

            cores.setFundo(jPnFundo.getBackground());
            cores.setMenus(jPnMenu.getBackground());

            dialog.cores(cores);
            dialog.manda(modelo);
            dialog.usuario(usua);
            dialog.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jTbVendasMouseClicked

    private void jTpesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTpesquisaKeyPressed
        consulta();
    }//GEN-LAST:event_jTpesquisaKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        consulta();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBtImprimirDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtImprimirDataActionPerformed
        barraInicioComprasData();
    }//GEN-LAST:event_jBtImprimirDataActionPerformed

    private void jBtImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtImprimirActionPerformed
        barraInicioCompra();
    }//GEN-LAST:event_jBtImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                consCompra dialog = new consCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void barraInicioComprasData() {
        // Progressbar
        new Thread() {

            @Override
            public void run() {

                super.run();

                jPb.setIndeterminate(true);

                jPb.setVisible(true);

                ImprimeComprasData();
                barraFim();
            }
        }
                .start();
    }

     public void barraInicioCompra() {
        // Progressbar
        new Thread() {

            @Override
            public void run() {

                super.run();

                jPb.setIndeterminate(true);

                jPb.setVisible(true);

                ImprimeCompras();
                
                barraFim();
            }
        }
                .start();
    }

    public void barraFim() {

        jPb.setIndeterminate(false);

        jPb.setVisible(false);

    }
    
    public void ImprimeComprasData() {

        //instancia a conexão
        Connection connection = new ConnectionFactory().getConnection();
        // note que estamos chamando o novo relatório
        InputStream inputStream = getClass().getResourceAsStream("/reportComprasData.jasper");

//      mapa de parâmetros do relatório
        Map parametros = new HashMap();
        SimpleDateFormat formate = new SimpleDateFormat("dd/MM/yyyy");
        String data = formate.format(jDateChooser1.getDate());
        parametros.put("datac", data);
        System.out.println(data);
        
        
        // outros possíveis parâmetros aqui...
        try {
            // abre o relatório 
            ReportUtils.openReport("Compras", inputStream, parametros, connection);

        } catch (JRException exc) {
            exc.printStackTrace();
        }

    }

    public void ImprimeCompras() {

        //instancia a conexão
        Connection connection = new ConnectionFactory().getConnection();
        // note que estamos chamando o novo relatório
        InputStream inputStream = getClass().getResourceAsStream("/reportCompras.jasper");

//      mapa de parâmetros do relatório
        Map parametros = new HashMap();
        parametros.put("data", "");

        // outros possíveis parâmetros aqui...
        try {
            // abre o relatório 
            ReportUtils.openReport("Compras", inputStream, parametros, connection);

        } catch (JRException exc) {
            exc.printStackTrace();
        }
    }
    
    public void usuario(String u) {
        usua = u;
    }

    public void tabela(Compras modelo) {
        //pegando do modelo e mandando para a tabela          
        tabela.addRow(new Object[]{
            modelo.getId_compra(),
            modelo.getFornecedor()+ " " + modelo.getCnpj_cpf(),
            modelo.getDatac(),
            modelo.getN_notafiscal(),
            modelo.getValor_total()
        });
    }

    public void consulta() {
        //instanciando Classe Prova() do Modelo
        Compras modelo = new Compras();

        //mandando pro set do modelo
        modelo.setFornecedor(jTpesquisa.getText());
        modelo.setDatac((String) jSelecionar.getSelectedItem());

        //criando a variavel para a tabela
        tabela = (javax.swing.table.DefaultTableModel) jTbVendas.getModel();
        tabela.setNumRows(0);

        CompraDAO dao = new CompraDAO();

        try {
            //evento do DAO  
            dao.consulta(modelo);

        } catch (HeadlessException | ParseException ex) {
            Logger.getLogger(consProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void cores(Cores cores) {
        jPnMenu.setBackground(cores.getMenus());
        jPnFundo.setBackground(cores.getFundo());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtImprimir;
    private javax.swing.JButton jBtImprimirData;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jPb;
    private javax.swing.JPanel jPnFundo;
    private javax.swing.JPanel jPnMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jSelecionar;
    private javax.swing.JTable jTbVendas;
    private javax.swing.JTextField jTpesquisa;
    // End of variables declaration//GEN-END:variables
}
