package com.igor.GUI;

import com.igor.DAO.VendaDAO;
import com.igor.DAO.ProdutoDAO;
import com.igor.modelo.Venda;
import com.igor.modelo.Cores;
import com.igor.modelo.Pessoas;
import com.igor.modelo.Produtos;
import java.awt.GridLayout;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IgorDev e Artur
 */
public class TelaVender extends javax.swing.JDialog {

    /**
     * Creates new form baixaProd
     */
    Double pTotal = 0.0;
    int cod, btEditar;
    private String usua;

    private static javax.swing.JComboBox comboclientes;
    private static javax.swing.table.DefaultTableModel tabela, carrinho;
    JFormattedTextField ftQuantidade = new JFormattedTextField();

    public TelaVender(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        desabilitar();
        desBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnFundo = new javax.swing.JPanel();
        jPnMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jBtNovo = new javax.swing.JButton();
        jBtLimpar = new javax.swing.JButton();
        jBtCadastrar = new javax.swing.JButton();
        jBtEditar = new javax.swing.JButton();
        jBtConsulta = new javax.swing.JButton();
        jTpreco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbpesquisa = new javax.swing.JTable();
        jTpesquisa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBtConcluir = new javax.swing.JButton();
        jSelecionar = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTbcarrinho = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTcod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCbCliente = new javax.swing.JComboBox();
        jBtExcluir = new javax.swing.JButton();
        jBtAdicionar = new javax.swing.JButton();
        jBtPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Vender - Aumbanco");

        jPnFundo.setBackground(new java.awt.Color(255, 255, 255));
        jPnFundo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPnMenu.setBackground(new java.awt.Color(57, 0, 255));

        jLabel2.setFont(new java.awt.Font("Aharoni", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vender");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/back_2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jBtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add_1.png"))); // NOI18N
        jBtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtNovoActionPerformed(evt);
            }
        });

        jBtLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/rewind.png"))); // NOI18N
        jBtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLimparActionPerformed(evt);
            }
        });

        jBtCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        jBtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCadastrarActionPerformed(evt);
            }
        });

        jBtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/note_edit.png"))); // NOI18N
        jBtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtEditarActionPerformed(evt);
            }
        });

        jBtConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jBtConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jBtNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jBtEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBtNovo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtCadastrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnMenuLayout = new javax.swing.GroupLayout(jPnMenu);
        jPnMenu.setLayout(jPnMenuLayout);
        jPnMenuLayout.setHorizontalGroup(
            jPnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnMenuLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPnMenuLayout.setVerticalGroup(
            jPnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel2)
                .addComponent(jButton2))
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTpreco.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jTpreco.setEnabled(false);
        jTpreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTprecoKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Preço(R$):");

        jTbpesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTbpesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Preço", "Qtd Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbpesquisa.setToolTipText("Dois Cliques Para Adicionar ao Carrinho");
        jTbpesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTbpesquisaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTbpesquisaFocusLost(evt);
            }
        });
        jTbpesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbpesquisaMouseClicked(evt);
            }
        });
        jTbpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTbpesquisaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTbpesquisa);
        if (jTbpesquisa.getColumnModel().getColumnCount() > 0) {
            jTbpesquisa.getColumnModel().getColumn(0).setHeaderValue("Código");
            jTbpesquisa.getColumnModel().getColumn(1).setHeaderValue("Nome");
            jTbpesquisa.getColumnModel().getColumn(2).setHeaderValue("Preço");
            jTbpesquisa.getColumnModel().getColumn(3).setHeaderValue("Qtd Estoque");
        }

        jTpesquisa.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jTpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTpesquisaKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Digite o:");

        jBtConcluir.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jBtConcluir.setText("Concluir");
        jBtConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtConcluirActionPerformed(evt);
            }
        });

        jSelecionar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSelecionar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Nome" }));

        jTbcarrinho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTbcarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Preço", "Quant. Compra", "Preço Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbcarrinho.setToolTipText("Dois Cliques Para Excluir do Carrinho");
        jTbcarrinho.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTbcarrinhoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTbcarrinhoFocusLost(evt);
            }
        });
        jTbcarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbcarrinhoMouseClicked(evt);
            }
        });
        jTbcarrinho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTbcarrinhoKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTbcarrinho);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Carrinho");

        jDateChooser1.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jDateChooser1.setMinSelectableDate(new Date());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Data:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Código:");

        jTcod.setEditable(false);
        jTcod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTcod.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Cliente:");

        jCbCliente.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jCbCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione" }));

        jBtExcluir.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        jBtExcluir.setText("Excluir");
        jBtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExcluirActionPerformed(evt);
            }
        });

        jBtAdicionar.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        jBtAdicionar.setText("Adicionar");
        jBtAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAdicionarActionPerformed(evt);
            }
        });

        jBtPesquisar.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        jBtPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search_2.png"))); // NOI18N
        jBtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnFundoLayout = new javax.swing.GroupLayout(jPnFundo);
        jPnFundo.setLayout(jPnFundoLayout);
        jPnFundoLayout.setHorizontalGroup(
            jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPnFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPnFundoLayout.createSequentialGroup()
                        .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnFundoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jCbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnFundoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtAdicionar))
                            .addGroup(jPnFundoLayout.createSequentialGroup()
                                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPnFundoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTcod, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPnFundoLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnFundoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtExcluir)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel5)
                        .addGap(187, 187, 187))
                    .addGroup(jPnFundoLayout.createSequentialGroup()
                        .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnFundoLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jBtConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnFundoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPnFundoLayout.setVerticalGroup(
            jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnFundoLayout.createSequentialGroup()
                .addComponent(jPnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPnFundoLayout.createSequentialGroup()
                        .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jCbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnFundoLayout.createSequentialGroup()
                                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPnFundoLayout.createSequentialGroup()
                                        .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(jTpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPnFundoLayout.createSequentialGroup()
                                        .addComponent(jBtAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(8, 8, 8)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPnFundoLayout.createSequentialGroup()
                        .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnFundoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16)
                        .addComponent(jTpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTprecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTprecoKeyPressed

    }//GEN-LAST:event_jTprecoKeyPressed

    private void jTpesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTpesquisaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            //manda o foco para o primeiro item da tabela
            jTbpesquisa.requestFocus();
            jTbpesquisa.getSelectionModel().clearSelection();
            jTbpesquisa.getSelectionModel().setSelectionInterval(0, 0);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jTpesquisa.getText().equals("")) {
                consulta();
            } else {
                //manda o foco para o primeiro item da tabela
                jTbpesquisa.requestFocus();
                jTbpesquisa.getSelectionModel().clearSelection();
                jTbpesquisa.getSelectionModel().setSelectionInterval(0, 0);
            }
        } else {
            consulta();
        }
    }//GEN-LAST:event_jTpesquisaKeyPressed


    private void jTbpesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbpesquisaMouseClicked
        //verifica se foi clicado
        if (evt.getClickCount() == 2) {
            carrinho();
        }

    }//GEN-LAST:event_jTbpesquisaMouseClicked

    private void jBtConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtConcluirActionPerformed
        cadastraVenda();
    }//GEN-LAST:event_jBtConcluirActionPerformed

    private void jTbcarrinhoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbcarrinhoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            tiradocarrinho();
        }
    }//GEN-LAST:event_jTbcarrinhoKeyPressed

    private void jTbcarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbcarrinhoMouseClicked
        if (evt.getClickCount() == 2) {
            tiradocarrinho();
        }

    }//GEN-LAST:event_jTbcarrinhoMouseClicked

    private void jTbpesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbpesquisaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //manda para o carrinho apertando o enter
            carrinho();
        }
    }//GEN-LAST:event_jTbpesquisaKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtNovoActionPerformed
        limpacampos();

        Venda modelo = new Venda();
        VendaDAO dao = new VendaDAO();
        Pessoas pes = new Pessoas();

        //parte da pesquisa de clientes para o combobox
        comboclientes = jCbCliente;
        comboclientes.removeAllItems();
        comboclientes.addItem("Selecione");
        try {
            dao.consultaCombo(pes);
        } catch (HeadlessException | ParseException ex) {
            Logger.getLogger(TelaVender.class.getName()).log(Level.SEVERE, null, ex);
        }

        //pegando o código da ultima venda e adicionando 1
        try {
            dao.UltimoCodigo(modelo);
        } catch (HeadlessException | ParseException ex) {
            Logger.getLogger(cadProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        int ultimoCod = modelo.getId_venda() + 1;
        jTcod.setText("" + ultimoCod);

        //setando a data para o dia atual
        jDateChooser1.setDate(new Date());

        habiBotoes();
        habilitar();
    }//GEN-LAST:event_jBtNovoActionPerformed

    private void jBtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jBtLimparActionPerformed

    private void jBtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCadastrarActionPerformed

    }//GEN-LAST:event_jBtCadastrarActionPerformed

    private void jBtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtEditarActionPerformed
        btEditar = 1;
        habilitar();
        habiBotoes();
    }//GEN-LAST:event_jBtEditarActionPerformed

    private void jBtConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtConsultaActionPerformed
        consVenda dialog = new consVenda(new javax.swing.JFrame(), true);
        Cores cores = new Cores();

        cores.setFundo(jPnFundo.getBackground());
        cores.setMenus(jPnMenu.getBackground());
        dialog.consulta();

        dialog.usuario(usua);
        dialog.cores(cores);
        dialog.setVisible(true);
    }//GEN-LAST:event_jBtConsultaActionPerformed

    private void jBtAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAdicionarActionPerformed
        carrinho();
    }//GEN-LAST:event_jBtAdicionarActionPerformed

    private void jTbpesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTbpesquisaFocusGained
        if (jTbpesquisa.getSelectedRowCount() > 0) {
            jBtAdicionar.setEnabled(true);
        } else {
            jBtAdicionar.setEnabled(false);
        }
    }//GEN-LAST:event_jTbpesquisaFocusGained

    private void jTbpesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTbpesquisaFocusLost

    }//GEN-LAST:event_jTbpesquisaFocusLost

    private void jBtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExcluirActionPerformed
        tiradocarrinho();
    }//GEN-LAST:event_jBtExcluirActionPerformed

    private void jTbcarrinhoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTbcarrinhoFocusGained
        if (jTbcarrinho.getSelectedRowCount() > 0) {
            jBtExcluir.setEnabled(true);
        } else {
            jBtExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_jTbcarrinhoFocusGained

    private void jTbcarrinhoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTbcarrinhoFocusLost

    }//GEN-LAST:event_jTbcarrinhoFocusLost

    private void jBtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisarActionPerformed
        consulta();
    }//GEN-LAST:event_jBtPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaVender dialog = new TelaVender(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void tabela(Venda modelo) {
        //pegando do modelo e mandando para a tabela          
        carrinho.addRow(new Object[]{
            modelo.getId_produto(),
            modelo.getNome_produto(),
            modelo.getPreco(),
            modelo.getQuantidade(),
            modelo.getQuantidade() * modelo.getPreco()
        });
    }

    public void manda(Venda modelo) {
        limpacampos();

        jTcod.setText("" + modelo.getId_venda());
        //manda a data para o Date chooser
        try {
            jDateChooser1.setDate(new SimpleDateFormat("dd/MM/yyyy").parse(modelo.getDatav()));
        } catch (ParseException ex) {
            Logger.getLogger(TelaVender.class.getName()).log(Level.SEVERE, null, ex);
        }

        //pesquisa para o combo
        VendaDAO dao = new VendaDAO();
        Pessoas pes = new Pessoas();

        //parte da pesquisa de clientes para o combobox
        comboclientes = jCbCliente;
        comboclientes.removeAllItems();
        comboclientes.addItem("Selecione");
        try {
            dao.consultaCombo(pes);
        } catch (HeadlessException | ParseException ex) {
            Logger.getLogger(TelaVender.class.getName()).log(Level.SEVERE, null, ex);
        }
        //seleciona o combobox
        jCbCliente.setSelectedItem(modelo.getNome_cliente());

        //consulta para tabela produtos venda (CARRINHO)
        try {
            dao.consultaProdutosVenda(modelo);
        } catch (HeadlessException | ParseException ex) {
            Logger.getLogger(TelaVender.class.getName()).log(Level.SEVERE, null, ex);
        }

        jTpreco.setText("" + modelo.getValorTotal());

        jBtNovo.setEnabled(false);
        jBtEditar.setEnabled(true);
        jBtLimpar.setEnabled(true);
    }

    public void usuario(String u) {
        usua = u;
    }

    public void consulta() {
        Produtos modelo = new Produtos();

        //mandando pro set do modelo
        modelo.setNome(jTpesquisa.getText());
        modelo.setPesquisa((String) jSelecionar.getSelectedItem());

        //criando a variavel para a tabela
        tabela = (javax.swing.table.DefaultTableModel) jTbpesquisa.getModel();
        tabela.setNumRows(0);

        ProdutoDAO dao = new ProdutoDAO();

        try {
            //evento do DAO
            dao.consultaVenda(modelo);

        } catch (HeadlessException | ParseException ex) {
            Logger.getLogger(consProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void combobox(Pessoas modelo) {
        comboclientes.addItem(modelo.getNomePessoa() + " " + modelo.getCPF_CNPJ());
    }

    public void limpar() {
        limpacampos();
        desBotoes();
        desabilitar();
    }

    public void limpacampos() {
        jDateChooser1.setDate(new Date());
        jTcod.setText("");
        jCbCliente.setSelectedItem("Selecione");
        tabela = (javax.swing.table.DefaultTableModel) jTbpesquisa.getModel();
        tabela.setNumRows(0);
        carrinho = (javax.swing.table.DefaultTableModel) jTbcarrinho.getModel();
        carrinho.setNumRows(0);

        jTpreco.setText("");
        pTotal = 0.0;
        jTpesquisa.setText("");
        jSelecionar.setSelectedItem("Selecione");
    }

    public void carrinho() {

        //criando a mensagem para selecionar quantidade
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(2, 1));
        JLabel label = new JLabel();
        label.setFont(new java.awt.Font("Tahoma", 1, 18));
        label.setText("Digite a quantia a ser vendida");
        JSpinner spiner = new JSpinner();
        spiner.setFont(new java.awt.Font("Tahoma", 1, 18));
        spiner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 999999999, 1));
        
        panel.add(label);
        panel.add(spiner);

        //mostrando na tela a mensagem para selecionar a quantidade
        int resultado = JOptionPane.showConfirmDialog(null, panel, "Quantidade", JOptionPane.OK_CANCEL_OPTION);

        if (resultado == JOptionPane.OK_OPTION) {

            //pegando a quantidade
            int qCompra = (int) spiner.getValue();
            if (qCompra == 0) {
                JOptionPane.showMessageDialog(null, "Zero(0) não é uma quantia válida");
                jTpesquisa.requestFocus();
            } else {

                //manda para outra tabela
                carrinho = (javax.swing.table.DefaultTableModel) jTbcarrinho.getModel();

                Object obj1 = (jTbpesquisa.getValueAt(jTbpesquisa.getSelectedRow(), 0));
                int codPesquisa = Integer.parseInt(obj1.toString());

                Object obj2 = (jTbpesquisa.getValueAt(jTbpesquisa.getSelectedRow(), 1));
                String nome = obj2.toString();

                Object obj3 = (jTbpesquisa.getValueAt(jTbpesquisa.getSelectedRow(), 2));
                Double valor = (Double) obj3;

                Double preco_total = valor * qCompra;

                carrinho.addRow(new Object[]{codPesquisa, nome, valor, qCompra, preco_total});

                tabela = (javax.swing.table.DefaultTableModel) jTbpesquisa.getModel();
                tabela.setNumRows(0);
                jTpesquisa.setText("");
                jTpesquisa.requestFocus();

                //Preco total
                Double precoT = pTotal;
                pTotal = (precoT + preco_total);
                jTpreco.setText("" + pTotal);

                jBtAdicionar.setEnabled(false);
            }
        }
    }

    public void tiradocarrinho() {
        Object obj1 = (jTbcarrinho.getValueAt(jTbcarrinho.getSelectedRow(), 4));
        Double valor = (Double) obj1;

        Double precoT = pTotal;
        Double precoP = valor;
        pTotal = (precoT - precoP);
        jTpreco.setText("" + pTotal);

        carrinho = (javax.swing.table.DefaultTableModel) jTbcarrinho.getModel();
        carrinho.removeRow(jTbcarrinho.getSelectedRow());
    }

    public void cadastraVenda() {

        Venda modelo = new Venda();

        if (jCbCliente.getSelectedItem().equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione um Cliente");
            jCbCliente.requestFocus();
        } else {

            carrinho = (DefaultTableModel) jTbcarrinho.getModel();

            //valida se tem preodutos no carrinho
            if (carrinho.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Selecione ao menos um produto para a venda");
                jTpesquisa.requestFocus();
            } else {

                //metodo para cadastrar a venda
                int resultado = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja confirmar a venda?");
                if (resultado == JOptionPane.YES_OPTION) {
                    VendaDAO dao = new VendaDAO();

                //manda os dados para o modelo
                    //seta CPF do cliente cortando a string para pesquisar o id no banco
                    String cliente = jCbCliente.getSelectedItem().toString();
                    String cortaCpf = cliente.substring(cliente.length() - 14);
                    modelo.setCnpf_cpf(cortaCpf);

                    modelo.setId_venda(Integer.parseInt(jTcod.getText()));
                    modelo.setDatav("" + new SimpleDateFormat("dd/MM/yyyy").format(jDateChooser1.getDate()));
                    modelo.setValorTotal(pTotal);

                    try {
                        dao.cadastra_Venda(modelo);
                    } catch (SQLException | HeadlessException | ParseException ex) {
                        Logger.getLogger(TelaVender.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    //pega numero de linhas da tabela pro while
                    int y = carrinho.getRowCount() - 1;

                    //cadastra todas as linhas da tabela
                    do {

                        //manda variaveis para o modelo
                        modelo.setId_venda(Integer.parseInt(jTcod.getText()));
                        modelo.setId_produto((int) carrinho.getValueAt(y, 0));
                        modelo.setPreco((double) carrinho.getValueAt(y, 2));
                        modelo.setQuantidade((int) carrinho.getValueAt(y, 3));

                        try {
                            dao.cadastra_ProdutosVenda(modelo);
                        } catch (SQLException ex) {
                            Logger.getLogger(TelaVender.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        y = y - 1;
                    } while (!(y < 0));
                    limpar();
                } else {
                    JOptionPane.showMessageDialog(null, "Venda não confirmada");
                }
            }
        }
    }

    public void tabela(Produtos modelo) {
        //pegando do modelo e mandando para a tabela          
        tabela.addRow(new Object[]{
            modelo.getcProd(),
            modelo.getNome(),
            modelo.getValor(),
            modelo.getQuantidade()});
    }

    public void cores(Cores cores) {
        jPnMenu.setBackground(cores.getMenus());
        jPnFundo.setBackground(cores.getFundo());
    }

    public void desBotoes() {
        jBtNovo.setEnabled(true);
        jBtLimpar.setEnabled(false);
        jBtCadastrar.setEnabled(false);
        jBtConcluir.setEnabled(false);
        jBtPesquisar.setEnabled(false);

        jBtEditar.setEnabled(false);
        btEditar = 0;

        jBtPesquisar.setEnabled(false);
        jBtAdicionar.setEnabled(false);
        jBtExcluir.setEnabled(false);
    }

    public void habiBotoes() {
        jBtNovo.setEnabled(false);
        jBtCadastrar.setEnabled(false);
        jBtLimpar.setEnabled(true);
        jBtConcluir.setEnabled(true);
        jBtPesquisar.setEnabled(true);

        jBtEditar.setEnabled(false);
    }

    public void habilitar() {
        jDateChooser1.setEnabled(true);
        jTcod.setEnabled(true);
        jCbCliente.setEnabled(true);
        jTbpesquisa.setEnabled(true);
        jTbcarrinho.setEnabled(true);
        jTbcarrinho.setEnabled(true);

        jTpesquisa.setEnabled(true);
        jSelecionar.setEnabled(true);
    }

    public void desabilitar() {
        jDateChooser1.setEnabled(false);
        jTcod.setEnabled(false);
        jCbCliente.setEnabled(false);
        jTbpesquisa.setEnabled(false);
        jTbcarrinho.setEnabled(false);

        jTbcarrinho.setEnabled(false);
        jTpesquisa.setEnabled(false);
        jSelecionar.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAdicionar;
    private javax.swing.JButton jBtCadastrar;
    private javax.swing.JButton jBtConcluir;
    private javax.swing.JButton jBtConsulta;
    private javax.swing.JButton jBtEditar;
    private javax.swing.JButton jBtExcluir;
    private javax.swing.JButton jBtLimpar;
    private javax.swing.JButton jBtNovo;
    private javax.swing.JButton jBtPesquisar;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCbCliente;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPnFundo;
    private javax.swing.JPanel jPnMenu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox jSelecionar;
    private javax.swing.JTable jTbcarrinho;
    private javax.swing.JTable jTbpesquisa;
    private javax.swing.JTextField jTcod;
    private javax.swing.JTextField jTpesquisa;
    private javax.swing.JTextField jTpreco;
    // End of variables declaration//GEN-END:variables
}
