package br.com.aumbanco.GUI;

import br.com.aumbanco.DAO.PessoaDAO;
import br.com.aumbanco.modelo.Cores;
import br.com.aumbanco.modelo.Pessoas;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class cadPessoas extends javax.swing.JDialog {

    /**
     * Creates new form cadPessoas
     *
     * @param parent
     * @param modal
     */
    int btEditar;
    String cliente_fornecedor, mascCpf;
    private String usua;

    public cadPessoas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        desabilitar();
        desBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnFundo = new javax.swing.JPanel();
        jLbCPF = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTemail = new javax.swing.JTextField();
        jPnMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jBtNovo = new javax.swing.JButton();
        jBtLimpar = new javax.swing.JButton();
        jBtCadastrar = new javax.swing.JButton();
        jBtEditar = new javax.swing.JButton();
        jBtPesquisa = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTcomp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jCbEstado = new javax.swing.JComboBox();
        jCbCidade = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTrua = new javax.swing.JTextField();
        jTnum = new javax.swing.JFormattedTextField();
        jTbairro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTfone = new javax.swing.JFormattedTextField();
        jTcpf = new javax.swing.JFormattedTextField();
        jTnome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pessoas - Aumbanco");

        jPnFundo.setBackground(new java.awt.Color(255, 255, 255));
        jPnFundo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLbCPF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLbCPF.setText("CPF:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Email:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Telefone:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Nome:");

        jTemail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPnMenu.setBackground(new java.awt.Color(51, 51, 255));

        jLabel2.setFont(new java.awt.Font("Aharoni", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastro de Pessoas");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/back_2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jBtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add_1.png"))); // NOI18N
        jBtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtNovoActionPerformed(evt);
            }
        });

        jBtLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/rewind.png"))); // NOI18N
        jBtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLimparActionPerformed(evt);
            }
        });

        jBtCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        jBtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCadastrarActionPerformed(evt);
            }
        });

        jBtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/note_edit.png"))); // NOI18N
        jBtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtEditarActionPerformed(evt);
            }
        });

        jBtPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jBtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtPesquisa)
                .addGap(88, 88, 88)
                .addComponent(jBtNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jBtEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBtNovo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtCadastrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnMenuLayout = new javax.swing.GroupLayout(jPnMenu);
        jPnMenu.setLayout(jPnMenuLayout);
        jPnMenuLayout.setHorizontalGroup(
            jPnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnMenuLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPnMenuLayout.setVerticalGroup(
            jPnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnMenuLayout.createSequentialGroup()
                .addGroup(jPnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Cidade:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Estado:");

        jTcomp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Complemento:");

        jCbEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "sim", " " }));
        jCbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbEstadoActionPerformed(evt);
            }
        });

        jCbCidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCbCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "poripá" }));
        jCbCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbCidadeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Rua:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Número:");

        jTrua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTnum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jTnum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnumActionPerformed(evt);
            }
        });

        jTbairro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Bairro:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTnum, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTcomp))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jTrua, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTrua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jTcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        try {
            jTfone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTfone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTfone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfoneActionPerformed(evt);
            }
        });

        try {
            jTcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTcpf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTnome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPnFundoLayout = new javax.swing.GroupLayout(jPnFundo);
        jPnFundo.setLayout(jPnFundoLayout);
        jPnFundoLayout.setHorizontalGroup(
            jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnFundoLayout.createSequentialGroup()
                .addComponent(jPnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPnFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTemail)
                    .addGroup(jPnFundoLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnFundoLayout.createSequentialGroup()
                        .addComponent(jTfone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTnome))
                .addContainerGap())
        );
        jPnFundoLayout.setVerticalGroup(
            jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnFundoLayout.createSequentialGroup()
                .addComponent(jPnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLbCPF)
                    .addComponent(jTfone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbEstadoActionPerformed
        Pessoas modelo = new Pessoas();
        modelo.setCodEstado(jCbEstado.getSelectedIndex());

        jCbCidade.removeAllItems();
        jCbCidade.addItem("Selecione");

        PessoaDAO dao = new PessoaDAO();
        dao.cidade(modelo);
    }//GEN-LAST:event_jCbEstadoActionPerformed

    private void jCbCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbCidadeActionPerformed

    private void jTfoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfoneActionPerformed

    private void jBtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtNovoActionPerformed
        limpacampos();

        JPanel painel = new JPanel();
        JComboBox combobox = new JComboBox();
        JLabel label = new JLabel();

        label.setText("Escolha o tipo da pessoa");
        combobox.addItem("Cliente");
        combobox.addItem("Fornecedor");
        painel.add(label);
        painel.add(combobox);

        int resultado = JOptionPane.showConfirmDialog(null, painel, "Fornecedor/Cliente", JOptionPane.PLAIN_MESSAGE);
        if (resultado == JOptionPane.OK_OPTION) {
            if (combobox.getSelectedItem().equals("Cliente")) {
                labelCPF();
            } else if (combobox.getSelectedItem().equals("Fornecedor")) {
                labelCNPJ();
            }

            PessoaDAO dao = new PessoaDAO();
            dao.estados();
            jTcpf.setText("");

            habiBotoes();
            habilitar();
        }
    }//GEN-LAST:event_jBtNovoActionPerformed


    private void jBtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jBtLimparActionPerformed

    private void jBtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCadastrarActionPerformed
        Pessoas modelo = new Pessoas();

        String email = jTemail.getText();

        if (jTnome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite um nome!");
            jTnome.requestFocus();
            return;
        } else if (jTcpf.getText().equals(mascCpf)) {
            JOptionPane.showMessageDialog(null, "Digite um CPF/CNPJ!");
            jTcpf.requestFocus();
            return;
        } else if (validaCpf(jTcpf.getText().replaceAll("[^0-9]", "")) == false) {
            JOptionPane.showMessageDialog(null, "Digite um CPF/CNPJ válido");
            jTcpf.requestFocus();
            return;
        } else if (jCbEstado.getSelectedItem().toString().equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione um estado!");
            jCbEstado.requestFocus();
            return;
        } else if (jCbCidade.getSelectedItem().toString().equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione uma cidade!");
            jCbCidade.requestFocus();
            return;
        } else if (jCbCidade.getSelectedItem().toString().equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione um  estado!");
            jCbCidade.requestFocus();
            return;
        } else if (jTbairro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite um bairro!");
            jTbairro.requestFocus();
            return;
        } else if (jTrua.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite uma rua!");
            jTrua.requestFocus();
            return;
        } else if (jTnum.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite um número!");
            jTnum.requestFocus();
            return;
            //validacao do email somente se a pessoa digitar
        } else if (!jTemail.getText().equals("")) {
            if (isEmailValid(email) == false) {
                JOptionPane.showMessageDialog(null, "Digite um e-mail válido!");
                jTemail.requestFocus();
                return;
            }
        }
        if (isEmailValid(email) == true || jTemail.getText().equals("")) {

            //se == 1 manda para o evento de salvar edicao
            if (btEditar == 1) {
                salvaEdicao(modelo);
            } else {

                PessoaDAO dao = new PessoaDAO();

                //validacao no banco para ver se nao tem a Primary Key
                modelo.setCPF_CNPJ(jTcpf.getText());
                try {
                    dao.consultaCPF_CNPJ(modelo);
                } catch (HeadlessException | ParseException ex) {
                    Logger.getLogger(cadPessoas.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (!(modelo.getCPF_CNPJ().equals(""))) {
                    JOptionPane.showMessageDialog(null, "CPF já cadastrado no Sistema." + modelo.getCPF_CNPJ());
                    jTcpf.requestFocus();
                } else {

                    //evento para salvar no banco
                    modelo.setCliente_fornecedor(cliente_fornecedor);
                    modelo.setNomePessoa(jTnome.getText());
                    modelo.setTelefone(jTfone.getText());
                    modelo.setCPF_CNPJ(jTcpf.getText());
                    modelo.setEstado(jCbEstado.getSelectedItem().toString());
                    modelo.setCidade(jCbCidade.getSelectedItem().toString());
                    modelo.setBairro(jTbairro.getText());
                    modelo.setRua(jTrua.getText());
                    modelo.setNum(jTnum.getText().replace(".", ""));
                    modelo.setComplemento(jTcomp.getText());
                    modelo.setEmail(jTemail.getText());
                    modelo.setHoraalteracao(new SimpleDateFormat("HH:mm dd/MM/yyyy").format(new Date()));
                    modelo.setUsuario(usua);

                    //CADASTRO NO BANCO
                    int resultado = JOptionPane.showConfirmDialog(null, "Deseja cadastrar o " + cliente_fornecedor + "?");
                    if (resultado == JOptionPane.YES_OPTION) {
                        try {
                            dao.cadastra(modelo);
                        } catch (SQLException ex) {
                            Logger.getLogger(cadPessoas.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!\n Cadastrado: " + jTnome.getText() + ".");
                        limpar();
                    } else {
                        JOptionPane.showMessageDialog(null, "Cadastro cancelado.");
                    }
                }
            }
        }
    }//GEN-LAST:event_jBtCadastrarActionPerformed

    private void jBtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtEditarActionPerformed
        btEditar = 1;
        habilitar();
        habiBotoes();
        jTcpf.setEnabled(false);
    }//GEN-LAST:event_jBtEditarActionPerformed

    private void jBtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisaActionPerformed
        consPessoas dialog = new consPessoas(new javax.swing.JFrame(), true);
        Cores cores = new Cores();

        cores.setFundo(jPnFundo.getBackground());
        cores.setMenus(jPnMenu.getBackground());
        dialog.consulta();

        dialog.cores(cores);
        dialog.usuario(usua);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtPesquisaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadPessoas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadPessoas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadPessoas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadPessoas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cadPessoas dialog = new cadPessoas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public boolean validaCpf(String catacpf) throws HeadlessException {

        System.out.println(catacpf);

        if (cliente_fornecedor.equals("cliente")) {

            if (catacpf.equals("00000000000") || catacpf.equals("11111111111") || catacpf.equals("22222222222")
                    || catacpf.equals("33333333333") || catacpf.equals("44444444444") || catacpf.equals("55555555555")
                    || catacpf.equals("66666666666") || catacpf.equals("77777777777") || catacpf.equals("88888888888")
                    || catacpf.equals("99999999999") || (catacpf.length() != 11)) {
                return false;
            }
            //validar cpf
            if (CNP.isValidCPF(catacpf) == false) {
                return false;
            } else {
                return true;
            }

        } else if (cliente_fornecedor.equals("fornecedor")) {
            if (CNP.isValidCNPJ(catacpf) == false) {
                return false;
            } else {
                return true;
            }
        }
        return true;
    }

    public void labelCNPJ() {
        System.out.println("CNPJ");
        cliente_fornecedor = "fornecedor";
        jLbCPF.setText("CNPJ:");
        try {
            jTcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));

        } catch (ParseException ex) {
            Logger.getLogger(cadPessoas.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        mascCpf = jTcpf.getText();
    }

    public void labelCPF() {
        System.out.println("CPF");
        cliente_fornecedor = "cliente";
        jLbCPF.setText("CPF:");
        try {
            jTcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));

        } catch (ParseException ex) {
            Logger.getLogger(cadPessoas.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        mascCpf = jTcpf.getText();
    }

    public void usuario(String u) {
        //recebe usuario logado da outra tela
        usua = u;
    }

    public static boolean isEmailValid(String email) {
        if ((email == null) || (email.trim().length() == 0)) {
            return false;
        }

        String emailPattern = "\\b(^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@([A-Za-z0-9-])+(\\.[A-Za-z0-9-]+)*((\\.[A-Za-z0-9]{2,})|(\\.[A-Za-z0-9]{2,}\\.[A-Za-z0-9]{2,}))$)\\b";
        Pattern pattern = Pattern.compile(emailPattern, Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }

    public void manda(Pessoas modelo) {
        limpacampos();

        if (modelo.getCliente_fornecedor().equals("cliente")) {
            labelCPF();
        } else if (modelo.getCliente_fornecedor().equals("fornecedor")) {
            labelCNPJ();
        }

        PessoaDAO dao = new PessoaDAO();
        dao.estados();
        jCbEstado.setSelectedItem(modelo.getEstado());

        modelo.setCodEstado(jCbEstado.getSelectedIndex());

        jCbCidade.removeAllItems();
        jCbCidade.addItem("Selecione");
        dao.cidade(modelo);
        jCbCidade.setSelectedItem(modelo.getCidade());

        jTnome.setText(modelo.getNomePessoa());
        jTcpf.setText(modelo.getCPF_CNPJ());
        jTfone.setText("" + modelo.getTelefone());
        jTbairro.setText(modelo.getBairro());
        jTrua.setText(modelo.getRua());
        jTnum.setText("" + modelo.getNum());
        jTcomp.setText(modelo.getComplemento());
        jTemail.setText(modelo.getEmail());

        jBtNovo.setEnabled(false);
        jBtEditar.setEnabled(true);
        jBtLimpar.setEnabled(true);
    }

    public void cores(Cores cores) {
        jPnMenu.setBackground(cores.getMenus());
        jPnFundo.setBackground(cores.getFundo());
    }

    public void limpar() {
        desBotoes();
        desabilitar();
        limpacampos();
    }

    public void desBotoes() {
        jBtNovo.setEnabled(true);
        jBtLimpar.setEnabled(false);
        jBtCadastrar.setEnabled(false);

        jBtEditar.setEnabled(false);
        btEditar = 0;
    }

    public void habiBotoes() {
        jBtNovo.setEnabled(false);
        jBtCadastrar.setEnabled(true);
        jBtLimpar.setEnabled(true);

        jBtEditar.setEnabled(false);
    }

    public void habilitar() {
        jTcomp.setEnabled(true);
        jTcpf.setEnabled(true);
        jTemail.setEnabled(true);
        jTfone.setEnabled(true);
        jTnome.setEnabled(true);
        jTnum.setEnabled(true);
        jTbairro.setEnabled(true);
        jTrua.setEnabled(true);
        jCbCidade.setEnabled(true);
        jCbEstado.setEnabled(true);
    }

    public void desabilitar() {
        jTcomp.setEnabled(false);
        jTcpf.setEnabled(false);
        jTemail.setEnabled(false);
        jTfone.setEnabled(false);
        jTnome.setEnabled(false);
        jTnum.setEnabled(false);
        jTbairro.setEnabled(false);
        jTrua.setEnabled(false);
        jCbCidade.setEnabled(false);
        jCbEstado.setEnabled(false);
    }

    public void limpacampos() {
        jTnome.setText("");
        jTfone.setText("");
        jTcpf.setText("");

        jCbEstado.removeAllItems();
        jCbEstado.addItem("Selecione");
        jCbEstado.setSelectedIndex(0);

        jCbCidade.removeAllItems();
        jCbCidade.addItem("Selecione");
        jCbCidade.setSelectedIndex(0);

        jTbairro.setText("");
        jTrua.setText("");
        jTnum.setText("");
        jTcomp.setText("");
        jTemail.setText("");
    }

    public void salvaEdicao(Pessoas modelo) {
        //evento para salvar edicao no banco
        modelo.setCliente_fornecedor(cliente_fornecedor);
        modelo.setNomePessoa(jTnome.getText());
        modelo.setTelefone(jTfone.getText());
        modelo.setCPF_CNPJ(jTcpf.getText());
        modelo.setEstado(jCbEstado.getSelectedItem().toString());
        modelo.setCidade(jCbCidade.getSelectedItem().toString());
        modelo.setBairro(jTbairro.getText());
        modelo.setRua(jTrua.getText());
        modelo.setNum(jTnum.getText().replace(".", ""));
        modelo.setComplemento(jTcomp.getText());
        modelo.setEmail(jTemail.getText());
        modelo.setHoraalteracao(new SimpleDateFormat("HH:mm dd/MM/yyyy").format(new Date()));
        modelo.setUsuario(usua);

        PessoaDAO dao = new PessoaDAO();

        int resposta = JOptionPane.showConfirmDialog(null, "Deseja editar o cadastro?");
        if (resposta == JOptionPane.YES_OPTION) {
            try {
                dao.atualiza(modelo);

            } catch (SQLException ex) {
                Logger.getLogger(cadProduto.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "O cadastro foi editado com sucesso.");
            limpar();
        } else {
            JOptionPane.showMessageDialog(null, "Edição não realizada.");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtCadastrar;
    private javax.swing.JButton jBtEditar;
    private javax.swing.JButton jBtLimpar;
    private javax.swing.JButton jBtNovo;
    private javax.swing.JButton jBtPesquisa;
    private javax.swing.JButton jButton1;
    public static javax.swing.JComboBox jCbCidade;
    public static javax.swing.JComboBox jCbEstado;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLbCPF;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPnFundo;
    private javax.swing.JPanel jPnMenu;
    private javax.swing.JTextField jTbairro;
    private javax.swing.JTextField jTcomp;
    private javax.swing.JFormattedTextField jTcpf;
    private javax.swing.JTextField jTemail;
    private javax.swing.JFormattedTextField jTfone;
    private javax.swing.JTextField jTnome;
    private javax.swing.JFormattedTextField jTnum;
    private javax.swing.JTextField jTrua;
    // End of variables declaration//GEN-END:variables
}
