/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.aumbanco.GUI;

import br.com.aumbanco.DAO.ProdutoDAO;
import br.com.aumbanco.DAO.UsuarioDAO;
import br.com.aumbanco.modelo.Cores;
import br.com.aumbanco.modelo.Produtos;
import br.com.aumbanco.modelo.Usuario;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IgorDev & Artur
 */
public final class TelaInicial extends javax.swing.JFrame {

    public String lg;
    public int u;
    Cores cores = new Cores();
    private static javax.swing.table.DefaultTableModel estoquebaixo;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();

        horario h = new horario();

        //maximizar
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        cores.setFundo(jPnFundo.getBackground());
        cores.setMenus(jPnMenu1.getBackground());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDgFundo = new javax.swing.JDialog();
        jColorChooser1 = new javax.swing.JColorChooser();
        jBtCorfundo = new javax.swing.JButton();
        jDgMenus = new javax.swing.JDialog();
        jColorChooser2 = new javax.swing.JColorChooser();
        jBtCorfundo1 = new javax.swing.JButton();
        jPnMenu1 = new javax.swing.JPanel();
        jLtitulo = new javax.swing.JLabel();
        jAlteraUsuario = new javax.swing.JButton();
        jBtSair = new javax.swing.JButton();
        jCdUsuarios = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLbLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jLusuario1 = new javax.swing.JLabel();
        jLtipo = new javax.swing.JLabel();
        jPnFundo = new javax.swing.JPanel();
        jBtVenda = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jBtProdutos = new javax.swing.JButton();
        jBtPessoas = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jBtConsProdutos = new javax.swing.JButton();
        jBtConsPessoas = new javax.swing.JButton();
        jBtConsCompra = new javax.swing.JButton();
        jBtConsVenda = new javax.swing.JButton();
        jBtCompra = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbEstoqueBaixo = new javax.swing.JTable();
        jPnMenu2 = new javax.swing.JPanel();
        jLhora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnCorfundo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jBtCorfundo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtCorfundo.setText("Escolher");
        jBtCorfundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCorfundoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDgFundoLayout = new javax.swing.GroupLayout(jDgFundo.getContentPane());
        jDgFundo.getContentPane().setLayout(jDgFundoLayout);
        jDgFundoLayout.setHorizontalGroup(
            jDgFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDgFundoLayout.createSequentialGroup()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDgFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtCorfundo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        jDgFundoLayout.setVerticalGroup(
            jDgFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDgFundoLayout.createSequentialGroup()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtCorfundo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtCorfundo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtCorfundo1.setText("Escolher");
        jBtCorfundo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCorfundo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDgMenusLayout = new javax.swing.GroupLayout(jDgMenus.getContentPane());
        jDgMenus.getContentPane().setLayout(jDgMenusLayout);
        jDgMenusLayout.setHorizontalGroup(
            jDgMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDgMenusLayout.createSequentialGroup()
                .addComponent(jColorChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDgMenusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtCorfundo1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        jDgMenusLayout.setVerticalGroup(
            jDgMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDgMenusLayout.createSequentialGroup()
                .addComponent(jColorChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtCorfundo1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tela Inicial - Aumbanco");
        setUndecorated(true);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPnMenu1.setBackground(new java.awt.Color(101, 154, 91));
        jPnMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPnMenu1MouseEntered(evt);
            }
        });

        jLtitulo.setFont(new java.awt.Font("Aharoni", 1, 60)); // NOI18N
        jLtitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLtitulo.setText("AUMBANCO");

        jAlteraUsuario.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jAlteraUsuario.setText("Alterar Usuario");
        jAlteraUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlteraUsuarioActionPerformed(evt);
            }
        });

        jBtSair.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jBtSair.setText("SAIR");
        jBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairActionPerformed(evt);
            }
        });

        jCdUsuarios.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jCdUsuarios.setText("Cadastrar Usuario");
        jCdUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCdUsuariosActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Usuário"));

        jLbLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLbLogin.setForeground(java.awt.Color.black);
        jLbLogin.setText("Usuario");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Usuário: ");

        jLNome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLNome.setForeground(java.awt.Color.black);
        jLNome.setText("Nome");

        jLusuario1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLusuario1.setForeground(java.awt.Color.black);
        jLusuario1.setText("Tipo:");

        jLtipo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLtipo.setForeground(java.awt.Color.black);
        jLtipo.setText("Tipo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLusuario1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbLogin)
                            .addComponent(jLtipo)))
                    .addComponent(jLNome))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbLogin)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLusuario1)
                    .addComponent(jLtipo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnMenu1Layout = new javax.swing.GroupLayout(jPnMenu1);
        jPnMenu1.setLayout(jPnMenu1Layout);
        jPnMenu1Layout.setHorizontalGroup(
            jPnMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnMenu1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPnMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jAlteraUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCdUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPnMenu1Layout.setVerticalGroup(
            jPnMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnMenu1Layout.createSequentialGroup()
                .addGroup(jPnMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnMenu1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLtitulo))
                    .addGroup(jPnMenu1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPnMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnMenu1Layout.createSequentialGroup()
                                .addComponent(jCdUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAlteraUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnFundo.setBackground(new java.awt.Color(255, 255, 255));
        jPnFundo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPnFundoMouseEntered(evt);
            }
        });

        jBtVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/shopping_cart_down.png"))); // NOI18N
        jBtVenda.setToolTipText("Venda de Produtos");
        jBtVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtVendaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Cadastro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jBtProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/shopping_cart_add_1.png"))); // NOI18N
        jBtProdutos.setToolTipText("Cadastrar Produtos");
        jBtProdutos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jBtProdutosFocusGained(evt);
            }
        });
        jBtProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtProdutosActionPerformed(evt);
            }
        });

        jBtPessoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_add.png"))); // NOI18N
        jBtPessoas.setToolTipText("Cadastrar Pessoas");
        jBtPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPessoasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtPessoas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Consultar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jBtConsProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/shopping_cart.png"))); // NOI18N
        jBtConsProdutos.setToolTipText("Consulta de Produtos");
        jBtConsProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtConsProdutosActionPerformed(evt);
            }
        });

        jBtConsPessoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        jBtConsPessoas.setToolTipText("Consulta de Pessoas");
        jBtConsPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtConsPessoasActionPerformed(evt);
            }
        });

        jBtConsCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/shopping_cart_up.png"))); // NOI18N
        jBtConsCompra.setToolTipText("Consulta de Compras");
        jBtConsCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtConsCompraActionPerformed(evt);
            }
        });

        jBtConsVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/shopping_cart_down.png"))); // NOI18N
        jBtConsVenda.setToolTipText("Consulta de Vendas");
        jBtConsVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtConsVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtConsProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtConsCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtConsPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtConsVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtConsProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtConsPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtConsVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtConsCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jBtCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/shopping_cart_up.png"))); // NOI18N
        jBtCompra.setToolTipText("Compra de Produtos");
        jBtCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCompraActionPerformed(evt);
            }
        });

        jTbEstoqueBaixo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Estoque Negativo - Clique para Atualizar"
            }
        ));
        jTbEstoqueBaixo.setToolTipText("Clique para atualizar");
        jTbEstoqueBaixo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbEstoqueBaixoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTbEstoqueBaixoMouseEntered(evt);
            }
        });
        jTbEstoqueBaixo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTbEstoqueBaixoKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTbEstoqueBaixo);

        javax.swing.GroupLayout jPnFundoLayout = new javax.swing.GroupLayout(jPnFundo);
        jPnFundo.setLayout(jPnFundoLayout);
        jPnFundoLayout.setHorizontalGroup(
            jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPnFundoLayout.setVerticalGroup(
            jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPnFundoLayout.createSequentialGroup()
                        .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addGroup(jPnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPnMenu2.setBackground(new java.awt.Color(101, 154, 91));
        jPnMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPnMenu2MouseEntered(evt);
            }
        });

        jLhora.setFont(new java.awt.Font("Aharoni", 1, 48)); // NOI18N
        jLhora.setForeground(new java.awt.Color(255, 255, 255));
        jLhora.setText("HH:mm");

        javax.swing.GroupLayout jPnMenu2Layout = new javax.swing.GroupLayout(jPnMenu2);
        jPnMenu2.setLayout(jPnMenu2Layout);
        jPnMenu2Layout.setHorizontalGroup(
            jPnMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnMenu2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLhora))
        );
        jPnMenu2Layout.setVerticalGroup(
            jPnMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnMenu2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLhora, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMnCorfundo.setText("Preferências");

        jMenuItem1.setText("Cor do Fundo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMnCorfundo.add(jMenuItem1);

        jMenuItem2.setText("Cor dos Menus");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMnCorfundo.add(jMenuItem2);

        jMenuBar1.add(jMnCorfundo);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPnMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPnFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jAlteraUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlteraUsuarioActionPerformed
        // TODO add your handling code here:

        //sai dando oportunidade de entrar com outro usuario
        new Login().setVisible(true);
        //codigo para salvar a saida do usuario do sistema
        Usuario modelo = new Usuario();
        UsuarioDAO dao = new UsuarioDAO();
        Date hora = new Date();
        SimpleDateFormat hora_formato = new SimpleDateFormat("HH:mm");
        SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");
        String data = out.format(new Date());
        modelo.setDatasaida(data);
        modelo.setLogin(jLbLogin.getText());
        modelo.setHorasaida(hora_formato.format(hora));
        try {
            dao.saida(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jAlteraUsuarioActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void jBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        //codigo para salvar a saida do usuario do sistema
        Usuario modelo = new Usuario();
        UsuarioDAO dao = new UsuarioDAO();
        Date hora = new Date();
        SimpleDateFormat hora_formato = new SimpleDateFormat("HH:mm");
        SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");
        String data = out.format(new Date());
        modelo.setDatasaida(data);
        modelo.setLogin(jLbLogin.getText());
        modelo.setHorasaida(hora_formato.format(hora));
        try {
            dao.saida(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_jBtSairActionPerformed

    private void jCdUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCdUsuariosActionPerformed
        if (jLtipo.getText().equals("administrador")) {
            cadUsuario dialog = new cadUsuario(new javax.swing.JFrame(), true);
            dialog.cores(cores);
            dialog.usuario(jLbLogin.getText());
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar esta tela\n"
                    + "Em caso de Duvida contate o Administrador");
        }
    }//GEN-LAST:event_jCdUsuariosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //chama dialog pra escolher cor de fundo
        jDgFundo.setSize(680, 400);
        jDgFundo.setLocationRelativeTo(null);
        jDgFundo.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jBtCorfundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCorfundoActionPerformed
        //volta para tela rinsipal trocando a cor do fundo
        cores.setFundo(jColorChooser1.getColor());
        jPnFundo.setBackground(cores.getFundo());
        jDgFundo.dispose();
    }//GEN-LAST:event_jBtCorfundoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //chama dialog pra escolher cor de fundo
        jDgMenus.setSize(680, 400);
        jDgMenus.setLocationRelativeTo(null);
        jDgMenus.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jBtCorfundo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCorfundo1ActionPerformed
        //volta para tela rinsipal trocando a cor do fundo
        cores.setMenus(jColorChooser2.getColor());
        jPnMenu1.setBackground(cores.getMenus());
        jPnMenu2.setBackground(cores.getMenus());
        jLhora.setForeground(cores.getMenus());

        jDgMenus.dispose();
    }//GEN-LAST:event_jBtCorfundo1ActionPerformed

    private void jBtCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCompraActionPerformed
        TelaComprar dialog = new TelaComprar(new javax.swing.JFrame(), true);
        dialog.cores(cores);
        dialog.usuario(jLbLogin.getText());
        dialog.setVisible(true);
    }//GEN-LAST:event_jBtCompraActionPerformed

    private void jBtConsPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtConsPessoasActionPerformed
        if (jLtipo.getText().equals("administrador")) {
            consPessoas dialog = new consPessoas(new javax.swing.JFrame(), true);
            dialog.consulta();
            dialog.cores(cores);
            dialog.usuario(jLbLogin.getText());
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar esta tela\n"
                    + "Em caso de Duvida contate o Administrador");
        }
    }//GEN-LAST:event_jBtConsPessoasActionPerformed

    private void jBtConsProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtConsProdutosActionPerformed
        if (jLtipo.getText().equals("administrador")) {
            consProdutos dialog = new consProdutos(new javax.swing.JFrame(), true);
            dialog.consulta();
            dialog.cores(cores);
            dialog.usuario(jLbLogin.getText());
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar esta tela\n"
                    + "Em caso de Duvida contate o Administrador");
        }
    }//GEN-LAST:event_jBtConsProdutosActionPerformed

    private void jBtPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPessoasActionPerformed
        if (jLtipo.getText().equals("administrador")) {
            cadPessoas dialog = new cadPessoas(new javax.swing.JFrame(), true);
            dialog.cores(cores);
            dialog.usuario(jLbLogin.getText());
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar esta tela\n"
                    + "Em caso de Duvida contate o Administrador");
        }
    }//GEN-LAST:event_jBtPessoasActionPerformed

    private void jBtProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtProdutosActionPerformed
        if (jLtipo.getText().equals("administrador")) {
            cadProduto dialog = new cadProduto(new javax.swing.JFrame(), true);
            dialog.cores(cores);
            dialog.usuario(jLbLogin.getText());
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar esta tela\n"
                    + "Em caso de Duvida contate o Administrador");
        }
    }//GEN-LAST:event_jBtProdutosActionPerformed

    private void jBtProdutosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBtProdutosFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtProdutosFocusGained

    private void jBtVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtVendaActionPerformed
        TelaVender dialog = new TelaVender(new javax.swing.JFrame(), true);
        dialog.cores(cores);
        dialog.usuario(jLbLogin.getText());
        dialog.setVisible(true);
    }//GEN-LAST:event_jBtVendaActionPerformed

    private void jBtConsCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtConsCompraActionPerformed
        if (jLtipo.getText().equals("administrador")) {
            consCompra dialog = new consCompra(new javax.swing.JFrame(), true);
            dialog.cores(cores);
            dialog.consulta();
            dialog.usuario(jLbLogin.getText());
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar esta tela\n"
                    + "Em caso de Duvida contate o Administrador");
        }
    }//GEN-LAST:event_jBtConsCompraActionPerformed

    private void jBtConsVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtConsVendaActionPerformed
        if (jLtipo.getText().equals("administrador")) {
            consVenda dialog = new consVenda(new javax.swing.JFrame(), true);
            dialog.cores(cores);
            dialog.consulta();
            dialog.usuario(jLbLogin.getText());
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar esta tela\n"
                    + "Em caso de Duvida contate o Administrador");
        }
    }//GEN-LAST:event_jBtConsVendaActionPerformed

    private void jTbEstoqueBaixoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbEstoqueBaixoKeyPressed
        consultaEstoqueBaixo();
    }//GEN-LAST:event_jTbEstoqueBaixoKeyPressed

    private void jPnFundoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnFundoMouseEntered
        horario h = new horario();
    }//GEN-LAST:event_jPnFundoMouseEntered

    private void jTbEstoqueBaixoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbEstoqueBaixoMouseClicked
        consultaEstoqueBaixo();
    }//GEN-LAST:event_jTbEstoqueBaixoMouseClicked

    private void jTbEstoqueBaixoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbEstoqueBaixoMouseEntered
        consultaEstoqueBaixo();
    }//GEN-LAST:event_jTbEstoqueBaixoMouseEntered

    private void jPnMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnMenu1MouseEntered
        horario h = new horario();
    }//GEN-LAST:event_jPnMenu1MouseEntered

    private void jPnMenu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnMenu2MouseEntered
        horario h = new horario();
    }//GEN-LAST:event_jPnMenu2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    public void tabela(Produtos modelo) {
        estoquebaixo.addRow(new Object[]{
            modelo.getNome()});
    }

    public void consultaEstoqueBaixo() {
        Produtos modelo = new Produtos();
        ProdutoDAO dao = new ProdutoDAO();

        estoquebaixo = (DefaultTableModel) jTbEstoqueBaixo.getModel();
        estoquebaixo.setNumRows(0);

        try {
            dao.EstoqueBaixo(modelo);
        } catch (HeadlessException | ParseException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (estoquebaixo.getColumnCount() > 0) {
            jTbEstoqueBaixo.setBackground(Color.red);
        } else {
            jTbEstoqueBaixo.setBackground(Color.white);
            estoquebaixo.setNumRows(jTbEstoqueBaixo.getHeight());
        }
    }

    public void setaLabels(Usuario modelo) {
        //manda os dados para as variaveis mustrando na tela
        jLbLogin.setText(modelo.getLogin());
        jLNome.setText(modelo.getNome());
        jLtipo.setText(modelo.getPermissao());
    }

    //Código do relogio da Interface
    public final class horario extends JFrame implements ActionListener {

        private javax.swing.Timer timer;

        public horario() {
            super("Horario");
            disparaRelogio();
        }

        public void disparaRelogio() {
            if (timer == null) {
                timer = new javax.swing.Timer(100, this);
                timer.setInitialDelay(0);
                timer.start();
            } else if (!timer.isRunning()) {
                timer.restart();
            }
        }

        @Override
        public void actionPerformed(ActionEvent ae) {
            Date hora = new Date();
            //estabelecendo formato
            SimpleDateFormat hora_formato = new SimpleDateFormat("HH:mm");
            //mandando para a Label
            jLhora.setText(hora_formato.format(hora));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAlteraUsuario;
    private javax.swing.JButton jBtCompra;
    private javax.swing.JButton jBtConsCompra;
    private javax.swing.JButton jBtConsPessoas;
    private javax.swing.JButton jBtConsProdutos;
    private javax.swing.JButton jBtConsVenda;
    private javax.swing.JButton jBtCorfundo;
    private javax.swing.JButton jBtCorfundo1;
    private javax.swing.JButton jBtPessoas;
    private javax.swing.JButton jBtProdutos;
    private javax.swing.JButton jBtSair;
    private javax.swing.JButton jBtVenda;
    private javax.swing.JButton jCdUsuarios;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JDialog jDgFundo;
    private javax.swing.JDialog jDgMenus;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbLogin;
    private static javax.swing.JLabel jLhora;
    private javax.swing.JLabel jLtipo;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JLabel jLusuario1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMnCorfundo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPnFundo;
    private javax.swing.JPanel jPnMenu1;
    private javax.swing.JPanel jPnMenu2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTbEstoqueBaixo;
    // End of variables declaration//GEN-END:variables

}
